
- hosts: all
  become: True
  tasks:

    - name: Create docker images folder
      file:
        name: "{{ item }}"
        state: directory
        owner: vagrant
        group: vagrant
      with_items:
        - /home/vagrant/docker_images/jenkins-sample
        - /home/vagrant/jenkins

    - name: Create Jenkins Dockerfile
      template:
        src: templates/jenkins/Dockerfile
        dest: /home/vagrant/docker_images/jenkins-sample/Dockerfile

    - name: Create jenkins sample job
      template:
        src: templates/jenkins/sample.xml
        dest: /home/vagrant/jenkins/sample.xml

    #Not using docker image module to avoid more requisites
    - name: Build jenkins with sample image
      shell: cd /home/vagrant/docker_images/jenkins-sample/ && docker build -t jenkins-sample .

    - name: Create a data container
      docker_container:
        name: mydata-jenkins
        image: busybox
        volumes:
          - /data

    - name: Create a jenkins container
      docker_container:
        name: jenkins
        image: jenkins-sample
        published_ports:
          - 8080:8080
        volumes_from:
          - mydata-jenkins

    - name: Wait jenkins
      wait_for:
        port: 8080
        delay: 10


